### ISSUE TITLE
Filepicker geht nicht nach Contao Update auf 3.4

### ISSUE THREAD

**Issue by soeren2k** [Kuestenschmiede/con4gis_forum#8]
Will man eine Datei als Bild für eine Kachel hochladen, erscheint zwar die Lightbox des Dateipickers, aber mit dem Fehler

"Fatal error: Class 'C4gForumModel' not found in /var/www/xxx/httpdocs/system/modules/core/controllers/BackendFile.php on line 87"

Link: https://community.contao.org/de/showthread.php?54223-Class-ProjekteModel-not-found-in-BackendFile-php&p=350334&viewfull=1#post350334

**Comment by coastforge-tdo** [comment]
Danke für deinen Beitrag.
Das scheint, wie aus deinem Link bereits hervorgeht, ein *Contao 3.4.0* Fehler zu sein, der mit der *3.4.1* behoben werden sollte. Sollte sich der Fehler auf unserer Seite jedoch schnell beheben/umgehen lassen, werden wir mit unserer nächsten Version einen eigenen Fix dafür freigeben.

English summary:
----------------------
@soeren2k mentioned, that picking a forum-tile-picture, under Contao 3.4, leads to an error (see above). This is a *Contao 3.4.0* bug that should be fixed with version *3.4.1*, but we consider fixing it on our side if there is a quick-and-easy solution

**Comment by coastforge-tdo** [comment]
We found a quick work-around https://github.com/Kuestenschmiede/con4gis_forum/commit/ba0c7b74d22aac3e8ccee25b122255663035ffc4 and will relase it soon with the next version :)
